version: 0.2
phases:
  build:
    commands:
      - echo "Building the project..."
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip lambda_function.py
post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip