version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Updating lambda Function.."
      - echo "Zipping deployment package..."
      - cd .\github-to-lambda-demo\
      - zip -r lambda_function.zip lambda_function.py
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://lambda_function.zip
      - echo "Generate logs"   
      - aws logs create-log-stream --log-group-name Github-lambda-group --log-stream-name github-lambda1-log-stream
      - echo "DONE!!"